/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  getStartedSidebar: [
    // Normal syntax:
    {
      type: "doc",
      id: "weaviate/index", // document ID
      label: "Overview", // sidebar label
    },
    {
      type: "doc",
      id: "weaviate/introduction", // document ID
      label: "About the docs", // sidebar label
    },
    {
      type: "category",
      label: "Quickstart",
      collapsible: true,
      collapsed: true,
      items: ["weaviate/quickstart/index", "weaviate/quickstart/local"],
    },
    {
      type: "category",
      label: "Client libraries",
      collapsible: true,
      collapsed: true,
      items: [
        "weaviate/client-libraries/index",
        {
          type: "category",
          label: "Python",
          collapsible: true,
          collapsed: true,
          items: [
            "weaviate/client-libraries/python/index",
            "weaviate/client-libraries/python/async",
            "weaviate/client-libraries/python/v3_v4_migration",
            "weaviate/client-libraries/python/python_v3",
          ],
        },
        {
          type: "category",
          label: "JavaScript and TypeScript",
          collapsible: true,
          collapsed: true,
          items: [
            "weaviate/client-libraries/typescript/index",
            "weaviate/client-libraries/typescript/typescript-v3",
            "weaviate/client-libraries/typescript/typescript-v2",
            "weaviate/client-libraries/typescript/v2_v3_migration",
          ],
        },
        "weaviate/client-libraries/java",
        "weaviate/client-libraries/go",
        "weaviate/client-libraries/community",
      ],
    },
    {
      type: "category",
      label: "Connect to Weaviate",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "weaviate/connections/index",
      },
      items: [
        "weaviate/connections/connect-cloud",
        "weaviate/connections/connect-local",
        "weaviate/connections/connect-custom",
        "weaviate/connections/connect-embedded",
        "weaviate/connections/connect-query",
      ],
    },
  ],
  modelProvidersSidebar: [
    {
      type: "autogenerated",
      dirName: "weaviate/model-providers",
    },
  ],
  conceptsSidebar: [
    {
      type: "autogenerated",
      dirName: "weaviate/concepts",
    },
  ],
  guidesSidebar: [
    {
      type: "category",
      label: "Configure Weaviate",
      link: {
        type: "doc",
        id: "weaviate/configuration/index",
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Compression",
          link: {
            type: "doc",
            id: "weaviate/configuration/compression/index",
          },
          collapsible: true,
          collapsed: true,
          items: [
            "weaviate/configuration/compression/pq-compression",
            "weaviate/configuration/compression/bq-compression",
            "weaviate/configuration/compression/sq-compression",
          ],
        },
        "weaviate/configuration/tenant-offloading",
        "weaviate/configuration/modules",
        "weaviate/configuration/backups",
        "weaviate/configuration/authentication",
        "weaviate/configuration/authorization",
        "weaviate/configuration/roles",
        "weaviate/configuration/persistence",
        "weaviate/configuration/monitoring",
        "weaviate/configuration/replication",
      ],
    },
    {
      type: "category",
      label: "Manage data",
      link: {
        type: "doc",
        id: "weaviate/manage-data/index",
      },
      collapsible: true,
      collapsed: true,
      items: [
        "weaviate/manage-data/collections",
        "weaviate/manage-data/create",
        "weaviate/manage-data/import",
        "weaviate/manage-data/read",
        "weaviate/manage-data/read-all-objects",
        "weaviate/manage-data/update",
        "weaviate/manage-data/delete",
        "weaviate/manage-data/cross-references",
        "weaviate/manage-data/multi-tenancy",
        "weaviate/manage-data/tenant-states",
        "weaviate/manage-data/migrate",
      ],
    },
    {
      type: "category",
      label: "Queries",
      link: {
        type: "doc",
        id: "weaviate/search/index",
      },
      collapsible: true,
      collapsed: true,
      items: [
        "weaviate/search/basics",
        "weaviate/search/similarity",
        "weaviate/search/bm25",
        "weaviate/search/hybrid",
        "weaviate/search/image",
        "weaviate/search/multi-vector",
        "weaviate/search/generative",
        "weaviate/search/rerank",
        "weaviate/search/aggregate",
        "weaviate/search/filters",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "doc",
        id: "weaviate/tutorials/index",
      },
      collapsible: true,
      collapsed: true,
      items: [
        "weaviate/tutorials/import",
        "weaviate/tutorials/cross-references",
        "weaviate/tutorials/import",
        "weaviate/tutorials/query",
        "weaviate/tutorials/wikipedia",
        "weaviate/tutorials/spark-connector",
        "weaviate/tutorials/modules",
      ],
    },
  ],
  referenceSidebar: [
    {
      type: "category",
      label: "API",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "weaviate/api/index",
      },
      items: [
        {
          type: "category",
          label: "Search (GraphQL | gRPC)",
          link: {
            type: "doc",
            id: "weaviate/api/graphql/index",
          },
          collapsible: true,
          collapsed: true,
          items: [
            "weaviate/api/graphql/get",
            "weaviate/api/graphql/aggregate",
            "weaviate/api/graphql/search-operators",
            "weaviate/api/graphql/filters",
            "weaviate/api/graphql/additional-operators",
            "weaviate/api/graphql/additional-properties",
            "weaviate/api/graphql/explore",
          ],
        },
        "weaviate/api/rest",
        "weaviate/api/grpc",
      ],
    },
    {
      type: "category",
      label: "Modules",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "weaviate/modules/index",
      },
      items: [
        "weaviate/modules/model_providers",
        "weaviate/modules/text2vec-contextionary",
        "weaviate/modules/img2vec-neural",
        "weaviate/modules/model_providers",
        "weaviate/modules/ref2vec-centroid",
        "weaviate/modules/qna-transformers",
        "weaviate/modules/qna-openai",
        "weaviate/modules/ner-transformers",
        "weaviate/modules/spellcheck",
        "weaviate/modules/sum-transformers",
        "weaviate/modules/custom-modules",
      ],
    },
    {
      type: "category",
      label: "Configuration",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Collection definition",
          link: {
            type: "doc",
            id: "weaviate/config-refs/schema/index",
          },
          collapsible: true,
          collapsed: true,
          items: [
            "weaviate/config-refs/schema/multi-vector",
            "weaviate/config-refs/schema/vector-index",
          ],
        },
        "weaviate/config-refs/datatypes",
        "weaviate/config-refs/distances",
        "weaviate/config-refs/env-vars",
        "weaviate/config-refs/status",
        "weaviate/config-refs/telemetry",
        "weaviate/config-refs/meta",
        "weaviate/config-refs/nodes",
        "weaviate/config-refs/oidc",
      ],
    },
  ],
  releasesSidebar: [
    {
      type: "category",
      label: "Release notes",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "weaviate/release-notes/index",
      },
      items: [
        "weaviate/release-notes/release_1_28",
        "weaviate/release-notes/release_1_27",
        "weaviate/release-notes/release_1_26",
        "weaviate/release-notes/release_1_25",
        "weaviate/release-notes/release_1_24",
        "weaviate/release-notes/release_1_23",
        {
          type: "category",
          label: "Older releases",
          collapsible: true,
          collapsed: true,
          items: [
            "weaviate/release-notes/older-releases/release_1_22",
            "weaviate/release-notes/older-releases/release_1_21",
            "weaviate/release-notes/older-releases/release_1_20",
            "weaviate/release-notes/older-releases/release_1_19",
            "weaviate/release-notes/older-releases/release_1_18",
            "weaviate/release-notes/older-releases/release_1_17",
            "weaviate/release-notes/older-releases/release_1_16",
          ],
        },
      ],
    },
  ],
  othersSidebar: [
    {
      type: "category",
      label: "Benchmarks",
      link: {
        type: "doc",
        id: "weaviate/benchmarks/index",
      },
      collapsible: true,
      collapsed: true,
      items: ["weaviate/benchmarks/ann"],
    },
    "weaviate/more-resources/faq",
    "weaviate/more-resources/glossary",
    "weaviate/more-resources/example-datasets",
  ],
  deploySidebar: ["deploy/index"],
  deployAwsSidebar: [
    {
      type: "autogenerated",
      dirName: "deploy/aws",
    },
  ],
  agentsSidebar: [
    {
      type: "autogenerated",
      dirName: "agents",
    },
  ],
  academySidebar: [
    {
      type: "autogenerated",
      dirName: "academy",
    },
  ],
  contributorSidebar: [
    {
      type: "doc",
      id: "contributor-guide/index", // document ID
      label: "Open-source at Weaviate", // sidebar label
    },
    {
      type: "category",
      label: "Getting started",
      collapsible: true,
      collapsed: false,
      link: {
        type: "doc",
        id: "contributor-guide/getting-started/index",
      },
      items: [
        "contributor-guide/getting-started/suggesting-enhancements",
        "contributor-guide/getting-started/reporting-bugs",
        "contributor-guide/getting-started/improving-docs",
        "contributor-guide/getting-started/writing-blogs",
        "contributor-guide/getting-started/git-and-github",
        "contributor-guide/getting-started/commit-guidelines",
      ],
    },
  ],
  contributorCoreSidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/weaviate-core",
    },
  ],
  contributorModulesSidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/weaviate-modules",
    },
  ],
  contributorContextionarySidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/contextionary",
    },
  ],
  contributorClientsSidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/weaviate-clients",
    },
  ],
  cloudSidebar: [
    {
      type: "doc",
      id: "cloud/index", // document ID
      label: "Overview", // sidebar label
    },
    {
      type: "doc",
      id: "cloud/quickstart", // document ID
      label: "Quickstart", // sidebar label
    },
    {
      type: "category",
      label: "Manage a cluster",
      collapsible: true,
      collapsed: false,
      items: [
        "cloud/manage-clusters/connect",
        "cloud/manage-clusters/create",
        "cloud/manage-clusters/status",
        "cloud/manage-clusters/upgrade",
      ],
    },
    {
      type: "category",
      label: "Tools",
      collapsible: true,
      collapsed: false,
      items: [
        "cloud/tools/collections-tool",
        "cloud/tools/explorer-tool",
        "cloud/tools/query-tool",
      ],
    },
    {
      type: "doc",
      id: "cloud/faq", // document ID
      label: "FAQ", // sidebar label
    },
  ],
  cloudWeaviateEmbeddings: [
    "cloud/embeddings/index",
    "cloud/embeddings/quickstart",
    "cloud/embeddings/models",
    "cloud/embeddings/administration",
  ],
  cloudAccountManagementSidebar: [
    "cloud/platform/billing",
    "cloud/platform/support-levels",
    "cloud/platform/version",
    "cloud/platform/create-account",
    "cloud/platform/manage-api-keys",
    "cloud/platform/multi-factor-auth",
    "cloud/platform/users-and-organizations",
  ],
  integrationsSidebar: [
    {
      type: "autogenerated",
      dirName: "integrations",
    },
  ],
};

module.exports = sidebars;
