// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  getStartedSidebar: [
    {
      type: "doc",
      id: "weaviate/index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Quickstart",
      link: {
        type: "doc",
        id: "weaviate/quickstart/index",
      },
      items: [
        "weaviate/quickstart/local",
        "weaviate/starter-guides/custom-vectors",
      ],
    },
    {
      type: "category",
      label: "Installation",
      link: {
        type: "doc",
        id: "weaviate/installation/index",
      },
      items: [
        "weaviate/installation/weaviate-cloud-services",
        "weaviate/installation/docker-compose",
        "weaviate/installation/kubernetes",
        "weaviate/installation/embedded",
        "weaviate/installation/spcs-integration",
      ],
    },
    {
      type: "category",
      label: "Connect to Weaviate",
      link: {
        type: "doc",
        id: "weaviate/connections/index",
      },
      items: [
        "weaviate/connections/connect-cloud",
        "weaviate/connections/connect-local",
        "weaviate/connections/connect-custom",
        "weaviate/connections/connect-embedded",
        "weaviate/connections/connect-query",
      ],
    },
    {
      type: "category",
      label: "Starter guides",
      link: {
        type: "doc",
        id: "weaviate/starter-guides/index",
      },
      items: [
        "weaviate/starter-guides/which-weaviate",
        "weaviate/starter-guides/generative",
        {
          type: "category",
          label: "Managing collections",
          link: {
            type: "doc",
            id: "weaviate/starter-guides/managing-collections/index",
          },
          items: [
            "weaviate/starter-guides/managing-collections/collections-scaling-limits",
          ],
        },
        {
          type: "category",
          label: "Managing resources (hot, warm, cold)",
          link: {
            type: "doc",
            id: "weaviate/starter-guides/managing-resources/index",
          },
          items: [
            "weaviate/starter-guides/managing-resources/compression",
            "weaviate/starter-guides/managing-resources/indexing",
            "weaviate/starter-guides/managing-resources/tenant-states",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Best practices",
      link: {
        type: "doc",
        id: "weaviate/best-practices/index",
      },
      items: ["weaviate/best-practices/code-generation"],
    },
  ],
  modelProvidersSidebar: [
    {
      type: "autogenerated",
      dirName: "weaviate/model-providers",
    },
  ],
  conceptsSidebar: [
    {
      type: "autogenerated",
      dirName: "weaviate/concepts",
    },
  ],
  guidesSidebar: [
    {
      type: "doc",
      id: "weaviate/guides",
      label: "Overview",
    },
    {
      type: "category",
      label: "How-to: Configure Weaviate",
      link: {
        type: "doc",
        id: "weaviate/configuration/index",
      },
      items: [
        {
          type: "category",
          label: "Compression",
          link: {
            type: "doc",
            id: "weaviate/configuration/compression/index",
          },
          items: [
            "weaviate/configuration/compression/pq-compression",
            "weaviate/configuration/compression/bq-compression",
            "weaviate/configuration/compression/sq-compression",
          ],
        },
        "weaviate/configuration/tenant-offloading",
        "weaviate/configuration/modules",
        "weaviate/configuration/backups",
        "weaviate/configuration/authentication",
        "weaviate/configuration/authorization",
        {
          type: "category",
          label: "RBAC",
          link: {
            type: "doc",
            id: "weaviate/configuration/rbac/index",
          },
          items: [
            "weaviate/configuration/rbac/configuration",
            "weaviate/configuration/rbac/manage-roles",
            "weaviate/configuration/rbac/manage-users",
          ],
        },
        "weaviate/configuration/persistence",
        "weaviate/configuration/monitoring",
        "weaviate/configuration/replication",
      ],
    },
    {
      type: "category",
      label: "How-to: Manage collections",
      link: {
        type: "doc",
        id: "weaviate/manage-collections/index",
      },
      items: [
        "weaviate/manage-collections/collection-operations",
        "weaviate/manage-collections/vector-config",
        "weaviate/manage-collections/generative-reranker-models",
        {
          type: "category",
          label: "Multi-tenancy",
          link: {
            type: "doc",
            id: "weaviate/manage-collections/multi-tenancy",
          },
          items: ["weaviate/manage-collections/tenant-states"],
        },
        "weaviate/manage-collections/multi-node-setup",
        "weaviate/manage-collections/migrate",
        "weaviate/manage-collections/cross-references",
      ],
    },
    {
      type: "category",
      label: "How-to: Manage objects",
      link: {
        type: "doc",
        id: "weaviate/manage-objects/index",
      },
      items: [
        "weaviate/manage-objects/create",
        "weaviate/manage-objects/import",
        "weaviate/manage-objects/read",
        "weaviate/manage-objects/read-all-objects",
        "weaviate/manage-objects/update",
        "weaviate/manage-objects/delete",
      ],
    },
    {
      type: "category",
      label: "How-to: Query & Search",
      link: {
        type: "doc",
        id: "weaviate/search/index",
      },
      items: [
        "weaviate/search/basics",
        "weaviate/search/similarity",
        "weaviate/search/bm25",
        "weaviate/search/hybrid",
        "weaviate/search/image",
        "weaviate/search/multi-vector",
        "weaviate/search/generative",
        "weaviate/search/rerank",
        "weaviate/search/aggregate",
        "weaviate/search/filters",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "doc",
        id: "weaviate/tutorials/index",
      },
      items: [
        "weaviate/tutorials/rbac",
        "weaviate/tutorials/multi-vector-embeddings",
        //"weaviate/tutorials/import",
        "weaviate/tutorials/cross-references",
        //"weaviate/tutorials/vector-provision-options",
        //"weaviate/tutorials/query",
        //"weaviate/tutorials/wikipedia",
        //"weaviate/tutorials/spark-connector",
        //"weaviate/tutorials/modules",
      ],
    },
  ],
  referenceSidebar: [
    {
      type: "category",
      label: "Client libraries",
      collapsible: false,
      className: "sidebar-main-category",
      link: {
        type: "doc",
        id: "weaviate/client-libraries/index",
      },
      items: [
        {
          type: "category",
          label: "Python",
          className: "sidebar-item",
          link: {
            type: "doc",
            id: "weaviate/client-libraries/python/index",
          },
          items: [
            "weaviate/client-libraries/python/async",
            "weaviate/client-libraries/python/notes-best-practices",
            {
              type: "link",
              label: "Reference manual",
              href: "https://weaviate-python-client.readthedocs.io/en/stable/index.html",
            },
          ],
        },
        {
          type: "category",
          label: "JavaScript/TypeScript",
          className: "sidebar-item",
          link: {
            type: "doc",
            id: "weaviate/client-libraries/typescript/index",
          },
          items: [
            "weaviate/client-libraries/typescript/notes-best-practices",
            {
              type: "link",
              label: "Reference manual",
              href: "https://weaviate.github.io/typescript-client/index.html",
            },
          ],
        },
        {
          type: "doc",
          id: "weaviate/client-libraries/java",
          className: "sidebar-item",
        },
        {
          type: "doc",
          id: "weaviate/client-libraries/go",
          className: "sidebar-item",
        },
        {
          type: "doc",
          id: "weaviate/client-libraries/community",
          className: "sidebar-item",
        },
      ],
    },
    // API section with divider
    {
      type: "html",
      value: "<hr class='sidebar-divider' />",
    },
    {
      type: "category",
      label: "APIs",
      className: "sidebar-main-category",
      link: {
        type: "doc",
        id: "weaviate/api/index",
      },
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Search API - GraphQL/gRPC",
          className: "sidebar-item",
          link: {
            type: "doc",
            id: "weaviate/api/search",
          },
          items: [
            "weaviate/api/graphql/get",
            "weaviate/api/graphql/aggregate",
            "weaviate/api/graphql/search-operators",
            "weaviate/api/graphql/filters",
            "weaviate/api/graphql/additional-operators",
            "weaviate/api/graphql/additional-properties",
            "weaviate/api/graphql/explore",
          ],
        },
        {
          type: "doc",
          id: "weaviate/api/rest",
          label: "RESTful API",
          className: "sidebar-item",
        },
      ],
    },
    {
      type: "html",
      value: "<hr class='sidebar-divider' />",
    },
    {
      type: "category",
      label: "Configuration",
      className: "sidebar-main-category",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Collection definition",
          className: "sidebar-item",
          link: {
            type: "doc",
            id: "weaviate/config-refs/schema/index",
          },
          items: [
            "weaviate/config-refs/schema/multi-vector",
            "weaviate/config-refs/schema/vector-index",
          ],
        },
        {
          type: "doc",
          id: "weaviate/config-refs/datatypes",
          className: "sidebar-item",
        },
        {
          type: "doc",
          id: "weaviate/config-refs/distances",
          className: "sidebar-item",
        },
        {
          type: "category",
          label: "Environment variables",
          className: "sidebar-item",
          link: {
            type: "doc",
            id: "weaviate/config-refs/env-vars/index",
          },
          items: ["weaviate/config-refs/env-vars/runtime-config"],
        },
        {
          type: "doc",
          id: "weaviate/config-refs/status",
          className: "sidebar-item",
        },
        {
          type: "doc",
          id: "weaviate/config-refs/telemetry",
          className: "sidebar-item",
        },
        {
          type: "doc",
          id: "weaviate/config-refs/meta",
          className: "sidebar-item",
        },
        {
          type: "doc",
          id: "weaviate/config-refs/nodes",
          className: "sidebar-item",
        },
        {
          type: "doc",
          id: "weaviate/config-refs/oidc",
          className: "sidebar-item",
        },
      ],
    },
  ],
  weaviateRecipesSidebar: [
    {
      type: "category",
      label: "Recipes",
      link: {
        type: "doc",
        id: "weaviate/recipes",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "weaviate/recipes", // Scans the folder docs/weaviate/recipes/
        },
      ],
    },
  ],
  othersSidebar: [
    {
      type: "category",
      label: "Releases",
      link: {
        type: "doc",
        id: "weaviate/release-notes/index",
      },
      items: [
        {
          type: "category",
          label: "Migration",
          link: {
            type: "doc",
            id: "weaviate/more-resources/migration/index",
          },
          items: [
            "weaviate/more-resources/migration/weaviate-1-30",
            "weaviate/more-resources/migration/weaviate-1-25",
            "weaviate/more-resources/migration/archive",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Benchmarks",
      link: {
        type: "doc",
        id: "weaviate/benchmarks/index",
      },
      items: ["weaviate/benchmarks/ann"],
    },
    {
      type: "category",
      label: "Modules",
      link: {
        type: "doc",
        id: "weaviate/modules/index",
      },
      items: [
        "weaviate/modules/text2vec-contextionary",
        "weaviate/modules/ref2vec-centroid",
        "weaviate/modules/qna-transformers",
        "weaviate/modules/qna-openai",
        "weaviate/modules/ner-transformers",
        "weaviate/modules/spellcheck",
        "weaviate/modules/sum-transformers",
        "weaviate/modules/custom-modules",
      ],
    },
    "weaviate/more-resources/faq",
    "weaviate/more-resources/glossary",
    "weaviate/more-resources/example-datasets",
  ],
  deploySidebar: ["deploy/index"],
  deployAwsSidebar: [
    {
      type: "autogenerated",
      dirName: "deploy/aws",
    },
  ],
  agentsSidebar: [
    "agents/index",
    {
      type: "category",
      label: "Query Agent",
      link: {
        type: "doc",
        id: "agents/query/index",
      },
      items: ["agents/query/usage", "agents/query/tutorial-ecommerce"],
    },
    {
      type: "category",
      label: "Transformation Agent",
      link: {
        type: "doc",
        id: "agents/transformation/index",
      },
      items: [
        "agents/transformation/usage",
        "agents/transformation/tutorial-enrich-dataset",
      ],
    },
    {
      type: "category",
      label: "Personalization Agent",
      link: {
        type: "doc",
        id: "agents/personalization/index",
      },
      items: [
        "agents/transformation/usage",
        "agents/personalization/tutorial-recipe-recommender",
      ],
    },
  ],
  agentsRecipesSidebar: [
    {
      type: "category",
      label: "Recipes",
      link: {
        type: "doc",
        id: "agents/recipes",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "agents/recipes", // Scans the folder docs/weaviate/recipes/
        },
      ],
    },
  ],
  academySidebar: [
    {
      type: "autogenerated",
      dirName: "academy",
    },
  ],
  contributorSidebar: [
    {
      type: "doc",
      id: "contributor-guide/index",
      label: "Open-source at Weaviate",
    },
    {
      type: "category",
      label: "Getting started",
      link: {
        type: "doc",
        id: "contributor-guide/getting-started/index",
      },
      items: [
        "contributor-guide/getting-started/suggesting-enhancements",
        "contributor-guide/getting-started/reporting-bugs",
        "contributor-guide/getting-started/improving-docs",
        "contributor-guide/getting-started/writing-blogs",
        "contributor-guide/getting-started/git-and-github",
        "contributor-guide/getting-started/commit-guidelines",
      ],
    },
  ],
  contributorCoreSidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/weaviate-core",
    },
  ],
  contributorModulesSidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/weaviate-modules",
    },
  ],
  contributorContextionarySidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/contextionary",
    },
  ],
  contributorClientsSidebar: [
    {
      type: "autogenerated",
      dirName: "contributor-guide/weaviate-clients",
    },
  ],
  cloudSidebar: [
    {
      type: "doc",
      id: "cloud/index",
      label: "Overview",
    },
    {
      type: "doc",
      id: "cloud/quickstart",
      label: "Quickstart",
    },
    {
      type: "category",
      label: "Manage a cluster",
      items: [
        "cloud/manage-clusters/connect",
        "cloud/manage-clusters/create",
        "cloud/manage-clusters/status",
        "cloud/manage-clusters/upgrade",
      ],
    },
    {
      type: "category",
      label: "Tools",
      items: [
        "cloud/tools/collections-tool",
        "cloud/tools/explorer-tool",
        "cloud/tools/query-tool",
      ],
    },
    {
      type: "doc",
      id: "cloud/faq",
      label: "FAQ",
    },
  ],
  cloudWeaviateEmbeddings: [
    "cloud/embeddings/index",
    "cloud/embeddings/quickstart",
    "cloud/embeddings/models",
    "cloud/embeddings/administration",
  ],
  cloudAccountManagementSidebar: [
    "cloud/platform/billing",
    "cloud/platform/support-levels",
    "cloud/platform/version",
    "cloud/platform/create-account",
    "cloud/platform/manage-api-keys",
    "cloud/platform/multi-factor-auth",
    "cloud/platform/users-and-organizations",
  ],
  integrationsSidebar: [
    "integrations/index",
    {
      type: "category",
      label: "Cloud Hyperscalers",
      link: {
        type: "doc",
        id: "integrations/cloud-hyperscalers/index",
      },
      items: [
        "integrations/cloud-hyperscalers/aws/index",
        "integrations/cloud-hyperscalers/google/index",
      ],
    },
    {
      type: "category",
      label: "Compute Infrastructure",
      link: {
        type: "doc",
        id: "integrations/compute-infrastructure/index",
      },
      items: [
        "integrations/compute-infrastructure/modal/index",
        "integrations/compute-infrastructure/replicate/index",
      ],
    },
    {
      type: "category",
      label: "Data Platforms",
      link: {
        type: "doc",
        id: "integrations/data-platforms/index",
      },
      items: [
        "integrations/data-platforms/airbyte/index",
        "integrations/data-platforms/aryn/index",
        "integrations/data-platforms/astronomer/index",
        "integrations/data-platforms/boomi/index",
        "integrations/data-platforms/box/index",
        "integrations/data-platforms/confluent/index",
        "integrations/data-platforms/context-data/index",
        "integrations/data-platforms/databricks/index",
        "integrations/data-platforms/firecrawl/index",
        "integrations/data-platforms/ibm/index",
        "integrations/data-platforms/unstructured/index",
      ],
    },
    {
      type: "category",
      label: "LLM and Agent Frameworks",
      link: {
        type: "doc",
        id: "integrations/llm-agent-frameworks/index",
      },
      items: [
        "integrations/llm-agent-frameworks/agno/index",
        "integrations/llm-agent-frameworks/composio/index",
        "integrations/llm-agent-frameworks/crewai/index",
        "integrations/llm-agent-frameworks/dspy/index",
        "integrations/llm-agent-frameworks/dynamiq/index",
        "integrations/llm-agent-frameworks/haystack/index",
        "integrations/llm-agent-frameworks/langchain/index",
        "integrations/llm-agent-frameworks/llamaindex/index",
        "integrations/llm-agent-frameworks/semantic-kernel/index",
      ],
    },
    {
      type: "category",
      label: "Operations",
      link: {
        type: "doc",
        id: "integrations/operations/index",
      },
      items: [
        "integrations/operations/arize/index",
        "integrations/operations/deepeval/index",
        "integrations/operations/langtrace/index",
        "integrations/operations/langwatch/index",
        "integrations/operations/nomic/index",
        "integrations/operations/ragas/index",
        "integrations/operations/wandb/index",
      ],
    },
  ],
  integrationsRecipesSidebar: [
    {
      type: "category",
      label: "Recipes",
      link: {
        type: "doc",
        id: "integrations/recipes",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "integrations/recipes",
        },
      ],
    },
  ],
};

module.exports = sidebars;
