/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  getStartedSidebar: [
    // Normal syntax:
    {
      type: 'doc',
      id: 'weaviate/index', // document ID
      label: 'Overview', // sidebar label
    },
    {
      type: 'doc',
      id: 'weaviate/introduction', // document ID
      label: 'About the docs', // sidebar label
    },
    {
      type: 'category',
      label: 'Quickstart',
      collapsible: true,
      collapsed: true,
      items: [
        'weaviate/quickstart/index',
        'weaviate/quickstart/local',
      ],
    },
    {
      type: 'category',
      label: 'Client libraries',
      collapsible: true,
      collapsed: true,
      items: [
        'weaviate/client-libraries/index',
        {
          type: 'category',
          label: 'Python',
          collapsible: true,
          collapsed: true,
          items: [
            'weaviate/client-libraries/python/index',
            'weaviate/client-libraries/python/async',
            'weaviate/client-libraries/python/v3_v4_migration',
            'weaviate/client-libraries/python/python_v3',
          ],
        },
        {
          type: 'category',
          label: 'JavaScript and TypeScript',
          collapsible: true,
          collapsed: true,
          items: [
            'weaviate/client-libraries/typescript/index',
            'weaviate/client-libraries/typescript/typescript-v3',
            'weaviate/client-libraries/typescript/typescript-v2',
            'weaviate/client-libraries/typescript/v2_v3_migration',
          ],
        },
        'weaviate/client-libraries/java',
        'weaviate/client-libraries/go',
        'weaviate/client-libraries/community',
      ],
    },
    {
      type: 'category',
      label: 'Connect to Weaviate',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'weaviate/connections/index'
      },
      items: [
        'weaviate/connections/connect-cloud',
        'weaviate/connections/connect-local',
        'weaviate/connections/connect-custom',
        'weaviate/connections/connect-embedded',
        'weaviate/connections/connect-query',
      ],
    },
  ],
  modelProvidersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'weaviate/model-providers'
    },
  ],
  conceptsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'weaviate/concepts'
    },
  ],
  guidesSidebar: [
    {
      type: 'category',
      label: 'Configure Weaviate',
      link: {
        type: 'doc',
        id: 'weaviate/configuration/index'
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Compression',
          link: {
            type: 'doc',
            id: 'weaviate/configuration/compression/index',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'weaviate/configuration/compression/pq-compression',
            'weaviate/configuration/compression/bq-compression',
            'weaviate/configuration/compression/sq-compression',
          ],
        },
        'weaviate/configuration/tenant-offloading',
        'weaviate/configuration/modules',
        'weaviate/configuration/backups',
        'weaviate/configuration/authentication',
        'weaviate/configuration/authorization',
        'weaviate/configuration/roles',
        'weaviate/configuration/persistence',
        'weaviate/configuration/monitoring',
        'weaviate/configuration/replication',
      ],
    },
    {
      type: 'category',
      label: 'Manage data',
      link: {
        type: 'doc',
        id: 'weaviate/manage-data/index'
      },
      collapsible: true,
      collapsed: true,
      items: [
        'weaviate/manage-data/collections',
        'weaviate/manage-data/create',
        'weaviate/manage-data/import',
        'weaviate/manage-data/read',
        'weaviate/manage-data/read-all-objects',
        'weaviate/manage-data/update',
        'weaviate/manage-data/delete',
        'weaviate/manage-data/cross-references',
        'weaviate/manage-data/multi-tenancy',
        'weaviate/manage-data/tenant-states',
        'weaviate/manage-data/migrate',
      ],
    },
    {
      type: 'category',
      label: 'Queries',
      link: {
        type: 'doc',
        id: 'weaviate/search/index'
      },
      collapsible: true,
      collapsed: true,
      items: [
        'weaviate/search/basics',
        'weaviate/search/similarity',
        'weaviate/search/bm25',
        'weaviate/search/hybrid',
        'weaviate/search/image',
        'weaviate/search/multi-vector',
        'weaviate/search/generative',
        'weaviate/search/rerank',
        'weaviate/search/aggregate',
        'weaviate/search/filters',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'weaviate/tutorials/index'
      },
      collapsible: true,
      collapsed: true,
      items: [
        'weaviate/tutorials/import',
        'weaviate/tutorials/cross-references',
        'weaviate/tutorials/import',
        'weaviate/tutorials/query',
        'weaviate/tutorials/wikipedia',
        'weaviate/tutorials/spark-connector',
        'weaviate/tutorials/modules',
      ],
    },
  ],
  referenceSidebar: [
    {
      type: 'category',
      label: 'Configuration',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Collection definition',
          link: {
            type: 'doc',
            id: 'weaviate/config-refs/schema/index'
          },
          collapsible: true,
          collapsed: true,
          items: [
            'weaviate/config-refs/schema/multi-vector',
            'weaviate/config-refs/schema/vector-index',
          ],
        },
        'weaviate/config-refs/datatypes',
        'weaviate/config-refs/distances',
        'weaviate/config-refs/env-vars',
        'weaviate/config-refs/status',
        'weaviate/config-refs/telemetry',
        'weaviate/config-refs/meta',
        'weaviate/config-refs/nodes',
        'weaviate/config-refs/oidc',
      ],
    },
  ],
  releasesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'weaviate/release-notes'
    },
  ],
  othersSidebar: [
    {
      type: 'category',
      label: 'Benchmarks',
      link: {
        type: 'doc',
        id: 'weaviate/benchmarks/index'
      },
      collapsible: true,
      collapsed: true,
      items: [
        'weaviate/benchmarks/ann'
      ],
    },
    'weaviate/more-resources/faq',
    'weaviate/more-resources/glossary',
    'weaviate/more-resources/example-datasets'
  ],
  academySidebar: [
    {
      type: 'autogenerated',
      dirName: 'academy'
    },
  ],
  contributorSidebar: [
    {
      type: 'autogenerated',
      dirName: 'contributor-guide'
    },
  ],
  wcsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'wcs'
    },
  ],
  integrationsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'integrations'
    },
  ],
};

module.exports = sidebars;
