blank_issues_enabled: true
contact_links:
  - name: Weaviate Community Forum
    url: https://forum.weaviate.io
    about: "Community-powered knowledge repository: search, ask questions, give feedback"

  - name: Community Support
    url: mailto:support@weaviate.io
    about: Contact us directly for private support inquiries
